FROM ruby:3.3.10

# Dependencias del sistema
RUN apt-get update -qq && \
  apt-get install -y build-essential libpq-dev curl

# Node & Corepack (Yarn moderno)
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
  apt-get install -y nodejs

RUN corepack enable && corepack prepare yarn@stable --activate

# Directorio de trabajo
WORKDIR /app

# Copiar Gems
COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

# Copiar proyecto
COPY . .

# Exponer puerto
EXPOSE 3000

# Rails server
CMD ["bash", "-c", "bundle install && bin/rails db:prepare && bin/rails server -b 0.0.0.0"]
